nome: Gerar Cobra

sobre:
  cronograma:
    - cron: "0 */12 * * *" # Funciona a cada 12 horas
  fluxo de trabalho_despacho:

permissões:
  conteúdo: escrever

empregos:
  construir:
    executa: ubuntu-latest

    etapas:
      - usos: ações/checkout@v4
      
      - usos: Platane/snk@v3
        id: snake-gif
        com:
          github_user_name: julianoandriolette # Substitua pelo seu nome de usuário do GitHub
          saídas: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?paleta=github escuro
            dist/github-contribution-grid-snake.gif
      
      - ses: crazy-max/ghaction-github-pages@v4
        com:
          target_branch: saída
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ segredos.GITHUB_TOKEN }} 
